### ISSUE TITLE
OIDC Documentation

### ISSUE THREAD

**Issue by aevans1987** [papermerge/documentation#103]
It has been a month since OIDC has been added to the software, can we please get documentation for how to do this? Even just the basics would be helpful, what are the Env vars?

**Comment by ciur** [comment]
OIDC was there, but never properly tested... and actually was not working anyway.

However, as part of next release (3.1) I tested and fixed the OIDC part.
In other words, OIDC (together with LDAP auth support) will be officially released, with proper documentation in 3.1.

I am updating the docs:

* https://docs.papermerge.io/3.1/setup/authentication/
* https://docs.papermerge.io/3.1/settings/auth/
* https://docs.papermerge.io/3.1/setup/docker-compose/#oauth-20

Notice though that docs are for 3.1, which in documentation as aliased as "3.1dev", which means "work in progress".
Again, in 3.0 you won't find any mention of OIDC/OAuth and code as buggy to the point where OIDC is unusable.

**Comment by aevans1987** [comment]
So am i right in thinking that you aren't supporting any OAuth/OIDC that isn't Google or Github? What about things like [Authentik](https://goauthentik.io/) or [Keycloak](https://www.keycloak.org/) and other self hosted options? Why is it being limited to Cloud platforms?

**Comment by ciur** [comment]
Yes, for 3.1 there will be only support for Google/GitHub cloud providers.
But I don't see any difficultly in extending solution to any OIDC provider or even make it generic.
Code for [authentication backends is here](https://github.com/papermerge/auth-server/tree/main/auth_server/backends)
